version: 2

jobs:
  build:
    docker:
      - image: rust:1
    steps:
      - checkout
      - run:
          name: Update environment
          command: |
            rustup update
      - run:
          name: Build
          command: cargo build --release
      - run:
          name: Test
          command: cargo test
